#!/usr/bin/env bash
###############################################################################
# This script follows the principles outlined here (see for details):
# Bash Boilerplate: https://github.com/xwmx/bash-boilerplate/blob/master/bash-subcommands
#
#
# cephtools
#
#
# Developed by the LMP bioinformatis team at the Minnesota Supercomputing Institute.
#
#
#
#
###############################################################################






###############################################################################
# Strict Mode
###############################################################################

# Treat unset variables and parameters other than the special parameters ‘@’ or
# ‘*’ as an error when performing parameter expansion. 
set -o nounset

# Exit immediately if a pipeline returns non-zero.
#
# NOTE: This can cause unexpected behavior. When using `read -rd ''` with a
# heredoc, the exit status is non-zero, even though there isn't an error.
set -o errexit

# Print a helpful message if a pipeline with non-zero exit code causes the
# script to exit as described above.
trap 'echo "Aborting due to errexit on line $LINENO. Exit code: $?" >&2' ERR

# Allow the above trap be inherited by all functions in the script.
set -o errtrace

# Return value of a pipeline is the value of the last (rightmost) command to
# exit with a non-zero status, or zero if all commands in the pipeline exit
# successfully.
set -o pipefail

# Set $IFS to only newline and tab.
IFS=$'\n\t'

###############################################################################
# Globals ###############################################################################


# This program's basename.
_ME="$(basename "${0}")"




