name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run make
        run: make
      
      - name: Package artifacts
        run: |
          mkdir -p release-package/cephtools-${{ github.ref_name }}
          cp -r build/bin release-package/cephtools-${{ github.ref_name }}/
          cp -r build/share release-package/cephtools-${{ github.ref_name }}/
          cp build/version.txt release-package/cephtools-${{ github.ref_name }}/
          cp license.txt release-package/cephtools-${{ github.ref_name }}/
          cp readme.md release-package/cephtools-${{ github.ref_name }}/
          cd release-package
          tar -czf ../cephtools-${{ github.ref_name }}.tar.gz cephtools-${{ github.ref_name }}/
          zip -r ../cephtools-${{ github.ref_name }}.zip cephtools-${{ github.ref_name }}/
      
      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            cephtools-${{ github.ref_name }}.tar.gz \
            cephtools-${{ github.ref_name }}.zip \
            --title "${{ github.ref_name }}" \
            --notes "Release ${{ github.ref_name }}"
